#!/bin/bash

initial_dir=$(pwd)

src=$(dirname $0)
src=$(cd $src;pwd)
source $src/testing-common-unit.sh

if [ "$action" == "export" ]; then
    trace "Exporting"
    echo "first: $(date): $(uuidgen)" > $data_dir/1.txt
    echo "second: $(date): $(uuidgen)" > $data_dir/2.txt
elif [ "$action" == "import" ]; then
    trace "Importing"
    for src in $data_dir/1.txt $data_dir/2.txt; do
        [ -f $src ] || error 77 "There is no source file $src"
        cp $src $home_dir || error 78 "Can't copy $src to $home_dir"
    done
fi
