#!/bin/bash
exec=./vault-clone-blobs

src=$(dirname $0)
src=$(cd $src;pwd)
source $src/vault-testing.sh

function assert_split {
    pattern=$1
    src_repo=
    port=
    user=
    host=
    src_type=

    split_git_uri $pattern

    res=
    case "$src_type" in
        ssh)
            res="SRC:user=$user,host=$host,port=$port,path=$src_repo"
            ;;
        local)
            res="SRC:path=$src_repo"
            ;;
        *)
            error 4 "Unsupported uri: $uri"
    esac

    if [ "$res" != "$2" ]; then
        error "FOR '$pattern': $res != $2"
        exit 1
    fi
}

# ssh:// form
assert_split ssh://user0@host1:/home/dir2 "SRC:user=user0,host=host1,port=,path=/home/dir2"
assert_split ssh://user0@host1:1/home/dir2 "SRC:user=user0,host=host1,port=1,path=/home/dir2"
assert_split ssh://user0@host1:12/home/dir2 "SRC:user=user0,host=host1,port=12,path=/home/dir2"
assert_split ssh://user0@host1.org:/home/dir2 "SRC:user=user0,host=host1.org,port=,path=/home/dir2"
assert_split ssh://host1.org:/home/dir2 "SRC:user=$(whoami),host=host1.org,port=,path=/home/dir2"

# user@host form
assert_split user0@host1:/home/dir2 "SRC:user=user0,host=host1,port=,path=/home/dir2"
assert_split user0@host1:1/home/dir2 "SRC:user=user0,host=host1,port=1,path=/home/dir2"
assert_split user0@host1:12/home/dir2 "SRC:user=user0,host=host1,port=12,path=/home/dir2"
assert_split user0@host1.org:/home/dir2 "SRC:user=user0,host=host1.org,port=,path=/home/dir2"
assert_split host1.org:/home/dir2 "SRC:user=$(whoami),host=host1.org,port=,path=/home/dir2"
assert_split host1.org\\:/home/dir2 "SRC:path=host1.org\\:/home/dir2"
