#!/bin/bash

initial_dir=$(pwd)

src=$(dirname $0)
src=$(cd $src;pwd)
source $src/vault-misc $src

cur_test="Begin"
function next_test {
    trace $@
    cur_test=$1
}

function test_failed {
    echo 'stdout {' >&2;
    cat $test_out >&2;
    echo '} stderr {' >&2;
    cat $test_err >&2;
    echo '}' >&2;
    error $1 "Test: $cur_test." ${@:2}
}

function check_is_vault_storage {
    d=$1
    [ -d $d ] || test_failed 7 "Not a dir $d"
    [ -f $d/config ] || test_failed 7 "Not a git storage"
    [ -d $d/blobs ] || test_failed 7 "Not a vault storage $d?"
}

trace "Test run in $TOP_PID"

empty_repo_archive=$src/../tests/empty-repo.tar.gz
[ -f $empty_repo_archive ] || test_failed 1 "No test vault archive"

is_success=true

test_dir=$(mktemp -t -d vault.XXXXXXXXXX)
test_out=$test_dir/stdout.txt
test_err=$test_dir/stderr.txt
cd $test_dir || test_failed 1 "Can't enter $test_dir"
normal_cleanup="$normal_cleanup; echo 'OK' 1>&2; cd $initial_dir; rm -rf $test_dir"
failed_cleanup="warn 'Dir $test_dir is left';$failed_cleanup;"


r1=$test_dir/v1
rout=$test_dir/external1
rout2=$test_dir/external2

next_test "Prepare $test_dir"
mkdir $r1 || test_failed 2 "Can't create $r1"
tar xf $empty_repo_archive -C $r1 || test_failed 4 "Can't extract archive"
cd $r1 || test_failed 5 "Can't enter $r1"
init_root_and_enter
storage_now=$r1/.git

next_test "Move to exiting dir"
mkdir $rout || test_failed 10 "Can't create $rout"
git-vault-move $rout 1>$test_out 2>$test_err \
    && test_failed 6 "Move to existing $rout shouldn't succeed"

next_test "Move to read-only dir"
chmod ug-w $rout || test_failed 12 "Can't chown $rout"
ro_dir=$rout/inaccessible
git-vault-move $ro_dir 1>$test_out 2>$test_err \
    && test_failed 6 "Move to RO dir $ro_dir shouldn't succeed"
[ -d $r1/.git ] || test_failed 7 "Not a dir $r1/.git"
check_is_vault_storage $storage_now
rmdir $rout || test_failed 11 "Dir $rout is not empty?"

next_test "Move out"
git-vault-move $rout \
    || test_failed 6 "Move to $rout"
storage_now=$rout
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now

next_test "Move out-of-tree dir to itself"
git-vault-move $rout 1>$test_out 2>$test_err \
    && test_failed 14 "Moving into self shouldn't succeed for $rout"

next_test "Move out to another dir"
git-vault-move $rout2 \
    || test_failed 6 "Move to $rout2"
storage_now=$rout2
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now

next_test "Move to read-only in-tree .git"
chmod ug-w $r1/.git || test_failed 12 "Can't chown $r1/.git"
git-vault-move $r1/.git 1>$test_out 2>$test_err \
    && test_failed 16 "Move to RO  $r1/.git shouldn't succeed"
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now
chmod ug+w $r1/.git || test_failed 12 "Can't chown back $r1/.git"

next_test "Move in"
git-vault-move $r1/.git \
    || test_failed 6 "Move to $r1/.git"
storage_now=$r1/.git
[ -d $rout ] && test_failed 7 "Dir $rout is left"
[ -d $r1/.git ] || test_failed 7 "Not a dir $r1/.git"
check_is_vault_storage $storage_now

next_test "Move in-tree dir to itself"
git-vault-move $r1 1>$test_out 2>$test_err \
    && test_failed 8 "Moving into self shouldn't succeed $r1.git"

next_test "Setup to check moving between filesystems"
other_fs=/dev/shm
[ -d /dev/shm ] || error 20 "Can't test further w/o /dev/shm used as other fs"
other_test_dir=$other_fs/$(basename $test_dir)
mkdir $other_test_dir || error 20 "Can't create $other_test_dir"
normal_cleanup="$normal_cleanup; rm -rf $other_test_dir"
failed_cleanup="warn 'Dir $other_test_dir is left';$failed_cleanup"

next_test "Move to other fs"

out_repo=$other_test_dir/v1

git-vault-move $out_repo \
    || test_failed 6 "Move to $out_repo"
storage_now=$out_repo
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now

next_test "Move from other fs"
git-vault-move $r1/.git \
    || test_failed 6 "Move from $out_repo"
[ -d $out_repo ] && error 23 "Dir should not be left: $out_repo"
storage_now=$r1/.git
[ -d $r1/.git ] || test_failed 7 "Not a dir $r1/.git"
check_is_vault_storage $storage_now

next_test "Move back to other fs"
git-vault-move $out_repo \
    || test_failed 6 "Move to $out_repo"
storage_now=$out_repo
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now

next_test "Move from other fs to out-of-tree"
git-vault-move $rout \
    || test_failed 6 "Move to $rout"
storage_now=$rout
[ -d $out_repo ] && test_failed 7 "Out dir is left: $out_repo"
[ -f $r1/.git ] || test_failed 7 "Not a file $r1/.git"
check_is_vault_storage $storage_now
